baseURL = "https://AkuSax.github.io/"
title = "Akul Saxena"

[pagination]
  pagerSize = 10

buildDrafts = false

[module]
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5"
  [[module.imports]]
    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5"

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', 'WC_POST_CSS']